### ISSUE TITLE
Product variation 

### ISSUE THREAD

**Issue by polavi-project** [polavi-project/ecommerce#172]
Product variation

**Comment by similik** [comment]
For the ones who installed the app before this task, Please make some changes to your Database schema following below

`/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

USE `<your database name>`; 

/* Foreign Keys must be dropped in the target to ensure that requires changes can be done*/

ALTER TABLE `cart_item` 
	DROP FOREIGN KEY `FK_CART_ITEM_PRODUCT`  , 
	DROP FOREIGN KEY `FK_CART_ITEM`  ;

ALTER TABLE `order_item` 
	DROP FOREIGN KEY `FK_ORDER`  ;

ALTER TABLE `product` 
	DROP FOREIGN KEY `FK_PRODUCT_ATTRIBUTE_GROUP`  ;


/* Alter table in target */
ALTER TABLE `cart_item` 
	ADD COLUMN `variant_group_id` int(10) unsigned   NULL after `total` , 
	ADD COLUMN `variant_options` text  COLLATE utf8_general_ci NULL after `variant_group_id` , 
	CHANGE `product_custom_options` `product_custom_options` text  COLLATE utf8_general_ci NULL after `variant_options` , 
	DROP COLUMN `variant_specification` ;

/* Alter table in target */
ALTER TABLE `cms_page_description` 
	DROP FOREIGN KEY `FK_CMS_PAGE_DESCRIPTION`  ;
ALTER TABLE `cms_page_description`
	ADD CONSTRAINT `FK_CMS_PAGE_DESCRIPTION` 
	FOREIGN KEY (`cms_page_description_cms_page_id`) REFERENCES `cms_page` (`cms_page_id`) ON DELETE CASCADE ;


/* Alter table in target */
ALTER TABLE `order_item` 
	ADD COLUMN `variant_group_id` int(10) unsigned   NULL after `total` , 
	ADD COLUMN `variant_options` text  COLLATE utf8_general_ci NULL after `variant_group_id` , 
	CHANGE `product_custom_options` `product_custom_options` text  COLLATE utf8_general_ci NULL after `variant_options` , 
	DROP COLUMN `variant_specification` , 
	ADD KEY `FK_ORDER_ITEM_PRODUCT`(`product_id`) , 
	DROP KEY `FK_PRODUCT` , 
	DROP FOREIGN KEY `FK_PRODUCT`  ;
ALTER TABLE `order_item`
	ADD CONSTRAINT `FK_ORDER_ITEM_PRODUCT` 
	FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`) ON DELETE NO ACTION ON UPDATE NO ACTION ;


/* Alter table in target */
ALTER TABLE `product` 
	ADD COLUMN `variant_group_id` int(10) unsigned   NULL after `group_id` , 
	ADD COLUMN `visibility` smallint(2)   NULL after `variant_group_id` , 
	CHANGE `image` `image` varchar(255)  COLLATE utf8_general_ci NULL after `visibility` , 
	ADD KEY `FK_PRODUCT_VARIANT_GROUP`(`variant_group_id`) ;
ALTER TABLE `product`
	ADD CONSTRAINT `FK_PRODUCT_VARIANT_GROUP` 
	FOREIGN KEY (`variant_group_id`) REFERENCES `variant_group` (`variant_group_id`) ON DELETE SET NULL ;


/* Create table in target */
CREATE TABLE `variant_group`(
	`variant_group_id` int(10) unsigned NOT NULL  auto_increment , 
	`attribute_group_id` int(10) unsigned NOT NULL  , 
	`attribute_one` int(10) unsigned NULL  , 
	`attribute_two` int(10) unsigned NULL  , 
	`attribute_three` int(10) unsigned NULL  , 
	`attribute_four` int(10) unsigned NULL  , 
	`attribute_five` int(10) unsigned NULL  , 
	`visibility` smallint(2) unsigned NOT NULL  DEFAULT 0 , 
	PRIMARY KEY (`variant_group_id`) , 
	KEY `FK_ATTRIBUTE_VARIANT_ONE`(`attribute_one`) , 
	KEY `FK_ATTRIBUTE_VARIANT_TWO`(`attribute_two`) , 
	KEY `FK_ATTRIBUTE_VARIANT_THREE`(`attribute_three`) , 
	KEY `FK_ATTRIBUTE_VARIANT_FOUR`(`attribute_four`) , 
	KEY `FK_ATTRIBUTE_VARIANT_FIVE`(`attribute_five`) , 
	KEY `FK_ATTRIBUTE_GROUP_VARIANT`(`attribute_group_id`) , 
	CONSTRAINT `FK_ATTRIBUTE_GROUP_VARIANT` 
	FOREIGN KEY (`attribute_group_id`) REFERENCES `attribute_group` (`attribute_group_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	CONSTRAINT `FK_ATTRIBUTE_VARIANT_FIVE` 
	FOREIGN KEY (`attribute_five`) REFERENCES `attribute` (`attribute_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	CONSTRAINT `FK_ATTRIBUTE_VARIANT_FOUR` 
	FOREIGN KEY (`attribute_four`) REFERENCES `attribute` (`attribute_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	CONSTRAINT `FK_ATTRIBUTE_VARIANT_ONE` 
	FOREIGN KEY (`attribute_one`) REFERENCES `attribute` (`attribute_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	CONSTRAINT `FK_ATTRIBUTE_VARIANT_THREE` 
	FOREIGN KEY (`attribute_three`) REFERENCES `attribute` (`attribute_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	CONSTRAINT `FK_ATTRIBUTE_VARIANT_TWO` 
	FOREIGN KEY (`attribute_two`) REFERENCES `attribute` (`attribute_id`) ON DELETE CASCADE ON UPDATE NO ACTION 
) ENGINE=InnoDB DEFAULT CHARSET='utf8' COLLATE='utf8_general_ci' COMMENT='Product variant group';

/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_AFTER_DELETE_ATTRIBUTE_OPTION`*/$$
CREATE
    TRIGGER `TRIGGER_AFTER_DELETE_ATTRIBUTE_OPTION` AFTER DELETE ON `attribute_option` 
    FOR EACH ROW BEGIN
                         DELETE FROM `product_attribute_value_index` WHERE `product_attribute_value_index`.option_id = OLD.attribute_option_id AND `product_attribute_value_index`.`attribute_id` = OLD.attribute_id;
                    END;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_AFTER_DELETE_TAX_CLASS`*/$$
CREATE
    TRIGGER `TRIGGER_AFTER_DELETE_TAX_CLASS` AFTER DELETE ON `tax_class` 
    FOR EACH ROW BEGIN
                         UPDATE `product` SET `product`.tax_class = 0 WHERE `product`.tax_class = OLD.tax_class_id;
                    END;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_AFTER_INSERT_PRODUCT`*/$$
CREATE
    TRIGGER `TRIGGER_AFTER_INSERT_PRODUCT` AFTER INSERT ON `product` 
    FOR EACH ROW BEGIN
                         INSERT INTO `product_price`(product_price_product_id, tier_price, customer_group_id, qty) VALUES(NEW.product_id, NEW.price, 1000, 1);
                         UPDATE `variant_group` SET visibility = (SELECT MAX(visibility) FROM `product` WHERE `product`.`variant_group_id` = new.variant_group_id AND `product`.`status` = 1 GROUP BY `product`.`variant_group_id`) WHERE `variant_group`.`variant_group_id` = new.variant_group_id;
                    END;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_ATTRIBUTE_OPTION_UPDATE`*/$$
CREATE
    TRIGGER `TRIGGER_ATTRIBUTE_OPTION_UPDATE` AFTER UPDATE ON `attribute_option` 
    FOR EACH ROW UPDATE `product_attribute_value_index` SET `product_attribute_value_index`.`attribute_value_text` = NEW.option_text
                        WHERE `product_attribute_value_index`.option_id = NEW.attribute_option_id AND `product_attribute_value_index`.attribute_id = NEW.attribute_id;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_PRODUCT_AFTER_UPDATE`*/$$
CREATE
    TRIGGER `TRIGGER_PRODUCT_AFTER_UPDATE` AFTER UPDATE ON `product` 
    FOR EACH ROW BEGIN
                        INSERT INTO `product_price`(`product_price_product_id`,`customer_group_id`, `qty`, `tier_price`) VALUES (NEW.product_id, 1000, 1, NEW.price) ON DUPLICATE KEY UPDATE tier_price = NEW.price;
                        DELETE FROM `product_attribute_value_index`
                        WHERE `product_attribute_value_index`.`product_id` = New.product_id 
                        AND `product_attribute_value_index`.`attribute_id` NOT IN (SELECT `attribute_group_link`.`attribute_id` FROM `attribute_group_link` WHERE `attribute_group_link`.`group_id` = NEW.group_id);
                        UPDATE `variant_group` SET visibility = (SELECT MAX(visibility) FROM `product` WHERE `product`.`variant_group_id` = NEW.variant_group_id AND `product`.`status` = 1 GROUP BY `product`.`variant_group_id`) WHERE `variant_group`.`variant_group_id` = NEW.variant_group_id;
                        UPDATE `variant_group` SET visibility = (SELECT MAX(visibility) FROM `product` WHERE `product`.`variant_group_id` = OLD.variant_group_id AND `product`.`status` = 1 GROUP BY `product`.`variant_group_id`) WHERE `variant_group`.`variant_group_id` = OLD.variant_group_id;
                    END;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_REMOVE_ATTRIBUTE_FROM_GROUP`*/$$
CREATE
    TRIGGER `TRIGGER_REMOVE_ATTRIBUTE_FROM_GROUP` AFTER DELETE ON `attribute_group_link` 
    FOR EACH ROW BEGIN
                        DELETE FROM `product_attribute_value_index` WHERE product_attribute_value_index.attribute_id = OLD.attribute_id AND product_attribute_value_index.product_id IN (SELECT product.product_id FROM product WHERE product.group_id = OLD.group_id);
                        DELETE FROM `variant_group` WHERE `variant_group`.`attribute_group_id` = OLD.group_id AND (`variant_group`.`attribute_one` = OLD.attribute_id OR `variant_group`.`attribute_two` = OLD.attribute_id OR `variant_group`.`attribute_three` = OLD.attribute_id OR `variant_group`.`attribute_four` = OLD.attribute_id OR `variant_group`.`attribute_five` = OLD.attribute_id);
                    END;
$$
DELIMITER ;


/* Alter Trigger in target */

DELIMITER $$
/*!50003 DROP TRIGGER *//*!50032 IF EXISTS*//*!50003 `TRIGGER_UPDATE_COUPON_USED_TIME_AFTER_CREATE_ORDER`*/$$
CREATE
    TRIGGER `TRIGGER_UPDATE_COUPON_USED_TIME_AFTER_CREATE_ORDER` AFTER INSERT ON `order` 
    FOR EACH ROW                     
                        BEGIN
                            UPDATE `coupon` SET `coupon`.used_time = `coupon`.used_time + 1 WHERE `coupon`.coupon = NEW.coupon;
                            IF (NEW.customer_id <> NULL) THEN
                                INSERT INTO `customer_coupon_use` (`customer_id`, `coupon`, `used_time`) VALUES (NEW.customer_id, NEW.coupon, 1)
                                    ON DUPLICATE KEY UPDATE `customer_coupon_use`.used_time = `customer_coupon_use`.used_time + 1;
                            END IF;
                        END;
$$
DELIMITER ;

 

/* The foreign keys that were dropped are now re-created*/

ALTER TABLE `cart_item` 
	ADD CONSTRAINT `FK_CART_ITEM_PRODUCT` 
	FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`) ON DELETE CASCADE ON UPDATE NO ACTION , 
	ADD CONSTRAINT `FK_CART_ITEM` 
	FOREIGN KEY (`cart_id`) REFERENCES `cart` (`cart_id`) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE `order_item` 
	ADD CONSTRAINT `FK_ORDER` 
	FOREIGN KEY (`order_item_order_id`) REFERENCES `order` (`order_id`) ON DELETE CASCADE ;

ALTER TABLE `product` 
	ADD CONSTRAINT `FK_PRODUCT_ATTRIBUTE_GROUP` 
	FOREIGN KEY (`group_id`) REFERENCES `attribute_group` (`attribute_group_id`) ON DELETE SET NULL ;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;`
